### ISSUE TITLE
Interest in being added as conda-forge feedstock maintainer?

### ISSUE THREAD

**Issue by matthewfeickert** [peraro/ninja#3]
:wave: As part of a [larger community project](https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/3) to try to do multi-platform packaging of the broader HEP simulation stack I've added `ninja` to conda-forge with @peraro's help: https://github.com/conda-forge/ninja-hep-ph-feedstock/.

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/ninja-hep-ph.svg)](https://anaconda.org/conda-forge/ninja-hep-ph) [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/ninja-hep-ph.svg)](https://anaconda.org/conda-forge/ninja-hep-ph)

Whenever I add something to conda-forge I like to also make sure that the project maintainers are aware of it and I also like to include them as feedstock maintainers so that they still have the ability to control the distribution of their project source code if they want to. This comes without any expectation of having to actually do the maintenance of the feedstock as it is unfair to expect additional work of project maintainers beyond the source code itself.

* @peraro Would you be interested in being listed as a conda-forge feedstock maintainer?

* Would you be open to a PR that would add conda-forge install instructions using `conda` and/or `pixi` to the README?

**Comment by peraro** [comment]
I appreciate the offer but I am not familiar with how conda-forge works, so there's no need to add me as a maintainer of the package for now.  You are very welcome to distribute `ninja` there, of course.

Adding conda-forge install instructions to the README here is a good idea.  Please, feel free to make a PR.

**Comment by peraro** [comment]
> Adding conda-forge install instructions to the README here is a good idea. Please, feel free to make a PR.

About this, maybe linking to https://github.com/conda-forge/ninja-hep-ph-feedstock/ in the README of `ninja` could be a good option, so that people can find the most complete and up-to-date documentation for it - and if anything is added or changes in conda-forge we don't need update the documentation twice.

**Comment by matthewfeickert** [comment]
> I appreciate the offer but I am not familiar with how conda-forge works, so there's no need to add me as a maintainer of the package for now. You are very welcome to distribute `ninja` there, of course.

Sounds good! :+1: Also fully understand and appreciate the feeling. :)

> About this, maybe linking to https://github.com/conda-forge/ninja-hep-ph-feedstock/ in the README of `ninja` could be a good option, so that people can find the most complete and up-to-date documentation for it - and if anything is added or changes in conda-forge we don't need update the documentation twice.

I definitely will link to the feedstock in the PR, but I'll still add some "copy paste" install instructions given that the bulk of the feedstock README it autogenerated by `conda-smithy` (the thing that automatically curates and maintains all conda-forge feedstocks) and there are plans to just remove all of the install instructions on the feedstocks READMEs and just link to a single website. While I understand that from a "we don't want to be responsible for telling you how to use all the tools" standpoint on their side, from a physicist's perspective I want to be able to visit a tool's repository and get going with it ASAP, and so having some simple install instructions along with the feedstock I think is generally a good idea, if you're okay with it.

**Comment by peraro** [comment]
Yes, I'm okay.  Thanks for taking care of it
